version: '3.8'
services: 
    api-service:
        build: .
        volumes: 
            - .:/usr/src/app/
        ports: 
            - 8080:5000
        # environment: 
        #     PORT: 5000
        #     FLASK_DEBUG: 1